### ISSUE TITLE
Unable to login with default credentials.

### ISSUE THREAD

**Issue by TestingBytes** [CiscoTestAutomation/xpresso#29]
I've gone through the recommended troubleshooting steps:

- all containers/apps are running
- admin/admin doesn't work
- docker-compose restart users auths and waited several minutes and no changes in behavior. 

Here's the tail of the users log:

> 
users_1                 | [2021-02-12 15:38:53 +0000] [1] [INFO] Starting gunicorn 19.7.1
users_1                 | [2021-02-12 15:38:53 +0000] [1] [DEBUG] Arbiter booted
users_1                 | [2021-02-12 15:38:53 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
users_1                 | [2021-02-12 15:38:53 +0000] [1] [INFO] Using worker: sync
users_1                 | [2021-02-12 15:38:53 +0000] [14] [INFO] Booting worker with pid: 14
users_1                 | [2021-02-12 15:38:53 +0000] [15] [INFO] Booting worker with pid: 15
users_1                 | [2021-02-12 15:38:54 +0000] [17] [INFO] Booting worker with pid: 17
users_1                 | [2021-02-12 15:38:54 +0000] [1] [DEBUG] 3 workers

Here's the tail of the auths logs:
>

auths_1                 | [2021-02-12 15:38:53 +0000] [1] [INFO] Starting gunicorn 19.7.1
auths_1                 | [2021-02-12 15:38:53 +0000] [1] [DEBUG] Arbiter booted
auths_1                 | [2021-02-12 15:38:53 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
auths_1                 | [2021-02-12 15:38:53 +0000] [1] [INFO] Using worker: sync
auths_1                 | [2021-02-12 15:38:53 +0000] [11] [INFO] Booting worker with pid: 11
auths_1                 | [2021-02-12 15:38:53 +0000] [13] [INFO] Booting worker with pid: 13
auths_1                 | [2021-02-12 15:38:53 +0000] [14] [INFO] Booting worker with pid: 14
auths_1                 | [2021-02-12 15:38:53 +0000] [1] [DEBUG] 3 workers

These logs were collected at 2021-02-12 15:46:53 +0000

Are there other steps recommended for troubleshooting login issues?

**Comment by littleyoda83** [comment]
Same. I cannot login using the default admin/admin

**Comment by adelph-cisco** [comment]
Hello @TestingBytes and @littleyoda83,

It seems there was is an issue with the auths service first time up causing this bug.
For now you should be able to fix this by restarting the auth service. 
-docker-compose stop auths
-docker-compose up -d auths
_This is being solved for the next release._

If this is not your issue, its possible there is a problem with your setup/server. Some common issues are:
1. Need to re-visit the readme.md steps
- permissions on the DB or log folders are not correct
- system flag for elastic to increase memory wasn’t set
- ADVERTISED_URL is not correct
2. has a firewall running
3. not enough resources so services came up before management was ready

I will be tracking this issue so feel free to respond.
