### ISSUE TITLE
schedules not picking up on modified testbeds

### ISSUE THREAD

**Issue by renato-alves-barros** [CiscoTestAutomation/xpresso#35]
If we modify a testbed which is currently associated with a schedule, that change is not picked up by the existing schedules.
For example, If I modify the device credentials on the testbed, the schedule will still use the old credential.
However, If I run the job directly, the updated credentials are used without problems.

**Comment by jcrwhite** [comment]
This is intended behaviour to fulfill an internal requirement. When creating a schedule, the system will snapshot that *exact* set of information to use when running and will not be affected by changes to the job, testbed, etc. To change the testbed, you would need to create a new schedule.
