### ISSUE TITLE
No Resources found error after login

### ISSUE THREAD

**Issue by sarath-baskar** [CiscoTestAutomation/xpresso#36]
After logging into the xpresso, I see there is an which pops out "No Resources found"

I even tried restarting the resources using below command, 
docker-compose restart resources

Version:21.3

**Comment by jcrwhite** [comment]
Please check section 3 of the readme. This is an issue with elasticsearch setup. Ensure the virtual memory values for the host are properly set and that the log and data directories have the correct permissions. After correcting those, bring both elasticsearch and resource containers down and back up.

**Comment by sarath-baskar** [comment]
I followed the steps and It actually resolved my issue,
Thanks!!!
