### ISSUE TITLE
Unhealthy services

### ISSUE THREAD

**Issue by rickbauer9482** [CiscoTestAutomation/xpresso#44]
Hi, I have a fresh build of Xpresso in my lab running on VM with 12 vCPUs, 32GB RAM, and 300GB storage and have two unhealthy services- xpresso_jenkinsengine-celery_1 and xpresso_users-celery_1. I've checked the docker logs for both services and don't see anything that jumps out, the only real complaint is that I'm running the worker with elevated privileges. 

Thanks...

**Comment by domachad** [comment]
Hi Rick, I can see that you are a Cisco employee. 

This means you have access to piestack. You can use it to raise Xpresso related issues.
Make sure you provide as many details as possible so we can better assist you

**Comment by rickbauer9482** [comment]
Thank you Douglas, how do I access piestack?

.:|:.:|:. Rick Bauer, CCDE #2014::8, CCIE #9482, DEVNET Professional
Technical Solutions Architect | Cisco Systems, Inc.
Enterprise Networking Campus Automation Center of Excellence
SNR: +1 408-894-7217 | ***@***.******@***.***>


From: Douglas Monteiro ***@***.***>
Date: Monday, April 4, 2022 at 10:41 AM
To: CiscoTestAutomation/xpresso ***@***.***>
Cc: Rick Bauer (rickbaue) ***@***.***>, Author ***@***.***>
Subject: Re: [CiscoTestAutomation/xpresso] Unhealthy services (Issue #44)

Hi Rick, I can see that you are a Cisco employee.

This means you have access to piestack. You can use it to raise Xpresso related issues.
Make sure you provide as many details as possible so we can better assist you

**Comment by domachad** [comment]
Hi Rick,
Here is the url: http://piestack.cisco.com/

**Comment by rickbauer9482** [comment]
Thank you.

.:|:.:|:. Rick Bauer, CCDE #2014::8, CCIE #9482, DEVNET Professional
Technical Solutions Architect | Cisco Systems, Inc.
Enterprise Networking Campus Automation Center of Excellence
SNR: +1 408-894-7217 | ***@***.******@***.***>


From: Douglas Monteiro ***@***.***>
Date: Wednesday, April 6, 2022 at 10:08 AM
To: CiscoTestAutomation/xpresso ***@***.***>
Cc: Rick Bauer (rickbaue) ***@***.***>, Author ***@***.***>
Subject: Re: [CiscoTestAutomation/xpresso] Unhealthy services (Issue #44)

Hi Rick,
Here is the url: http://piestack.cisco.com/

**Comment by domachad** [comment]
Great. I will close the issue, but please open a ticket on piestack whenever you're ready.
